services:
  - type: web
    name: firstlook-digital
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SERVER_PORT
        value: 10000
      - key: SPRING_PROFILES_ACTIVE
        value: prod
